apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80      # Port accessible externally
      targetPort: 3000  # Container port defined in deployment
  type: LoadBalancer  # Use "ClusterIP" if you don't need external access
